# AU template: https://github.com/majkinetor/au-packages-template

version: '{build}'
max_jobs: 1
image: WMF 5
clone_depth: 5
branches:
  only:
  - master
#build:
#  verbosity: minimal

environment:
  # Set au version to use or omit to use the latest. Specify branch name to use development version from Github
  #au_version: latest
  au_push: true

  # Github token to commit pushed packages to repository
  github_user_repo: bdukes/chocolatey-packages
  github_api_key:
    secure: Czr5so4ZCPwuFZlkUyVRmKlVkJZ5kBQOSCdBlssySQloUZiY85Smg7FNXtT9L7BQ


  # Mail credentials - for error notifications
  mail_user:
    secure: +xPHXyY0bzpb3roN9sl0PdeggcJ2L1MYIYkDSXjNG2c=
  mail_pass:
    secure: 70TPhBmRfbajaGAkq3MuYQ==
  mail_server: smtp.gmail.com
  mail_port: 587
  mail_enablessl: true

  # ID of the gist used to save run results - create a gist under the github_user (secret or not) and grab the id - https://gist.github.com/name/id
  # Optional, leave empty to create anonymous gist
  gist_id: fd3d636b9b4617772f9b99ceb88838fa

  # Chocolatey API key - to push updated packages
  api_key:
    secure: e8dwnu8NXv/wQkK5f8myhKi4ShcQxDkD65h44prLBOhyXVGqC0BJhYfY7M9Av73V

init:
- git config --global user.email "bdukes@engagesoftware.com"
- git config --global user.name "Brian Dukes (via AppVeyor)"
- git config --global core.safecrlf false

install:
- ps: 'Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version'
- ps: $PSVersionTable
- ps: |
    $x=$null; $is_branch = ($Env:au_version -ne $null) -and ([version]::TryParse($Env:au_version, [ref]$x) -eq $false)
    if ($is_branch) {
        pushd ..
            git clone -q https://github.com/majkinetor/au.git
            cd au
            git fetch
            git checkout -q $Env:au_version
            ./build.ps1 -Install -NoChocoPackage
        popd
    } else {
        Install-PackageProvider -Name NuGet -Force
        Set-PSRepository -Name PSGallery -InstallationPolicy Trusted

        $params = @{ Name = 'au' }
        if ( $Env:au_version -ne $null ) { $params.MinimumVersion = $Env:au_version }
        Install-Module @params

        Get-Module au -ListAvailable | select Name, Version
    }

build_script:
- ps: |
    ./au/update_all.ps1

#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
- path: update_info.xml
- path: Update-AUPackages.md

notifications:
- provider: Email
  to: $(mail_user)
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

